### ISSUE TITLE
Streamline Setup instructions

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#101]
# User Story

As a developer, I have easy to follow instructions, so that I can set up the repo without too much pain.

# Acceptance Criteria

- [ ] Setup instructions are similar to those for W21 jpa03-STARTER (SETUP-FULL, SETUP-QUICKSTART)
- [ ] setHerokuVars.py script is modified to make `javascript/.env.production` optional
- [ ] pom.xml is modified to use `SPRING_PROPERTIES` instead of `HEROKU_PROPERTIES`
- [ ] custom values needs for the application (e.g. ucsb api key and MongoDB URL) are set properly

**Comment by jvoucsb** [comment]
Pulled in #100
