### ISSUE TITLE
Left align "schedules" page, "update schedule" page, and "create schedule" page.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#106]
When you log in, you get an additional menu option for Schedules.

Currently, in the component `javascript/src/main/components/Schedule/ScheduleTable.js`, the fields for name and description are centered.

It would be preferable if both the data in the table, and the table headers for these two fields were left aligned.   

This can likely be done by simply adding the field `align: "left"` to the javascript object that defines the table structure, and `headerAlign: "left"` to affect the headers.

Documentation: https://react-bootstrap-table.github.io/react-bootstrap-table2/docs/column-props.html#columnalign-string-function

This image shows how it looks now.

![image](https://user-images.githubusercontent.com/1119017/108116933-21ffb480-7051-11eb-881e-5b05f5665f84.png)

# User Story

* As a logged-in user 
* I can see schedule data left aligned
* so that the information is easier to understand and edit

# Acceptance Criteria

- [x] Data and header for name column are left aligned
- [x] Data and header for description column are left aligned

# Implementation Todos

In `javascript/src/main/components/Schedule/ScheduleTable.js` find this code and add in the `align: "left"` and `headerAlign: "left" to the object for `name` and the one for `description`.

```
 const columns = [{
    dataField: 'id',
    text: 'id'
  }, {
    dataField: 'name',
    text: 'Name'
  },
  {
    dataField: 'description',
    text: 'Description'
  },
```

# Testing:

For this change, it may not be necessary to add additional tests, but existing tests should all pass.

However, if you do want to try to write tests for it, this may help:

https://medium.com/@the_teacher/how-to-test-a-react-components-css-styles-with-react-testing-library-rtl-styled-components-43f744334528

**Comment by AnikaArora** [comment]
Made a new branch: 5pm-1-leftAlign
