### ISSUE TITLE
In the results table, cell values for section rows don't need to be tabbed since they are already differentiated by color.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#110]
# User Story

* As a user
* I can see course search results indented consistently
* So that the table is easier to read

# Discussion

In the results table, cell values for section rows don't need to be tabbed since they are already differentiated by color.

Do a basic course search from the home page, such as the one shown below.  As you can see, the "secondaries" (i.e. sections that are not multiples of 100) are right aligned, while the primaries are left aligned.   They also have different background colors.

![image](https://user-images.githubusercontent.com/1119017/108118370-1dd49680-7053-11eb-9a7b-2ee5583ef57f.png)

This is done by the following code:

```
 const rowStyle = (row, rowIndex) => {
    return  (row.section % 100 == 0)? {backgroundColor: '#CEDEFA'}: {backgroundColor: '#EDF3FE'};
  }
  const dataAlignment = (cell, row) => {
    const alignmnet = (row.section % 100 == 0)? 'left': 'right';
    return alignmnet
  }
```

It's not necessary to differentiate both by color and by indentation, so let's change the alignment code so that everything is aligned to the left.

There is a test that will have to be updated as well.  The purist "TDD" approach would be to update the test first.

```
test("check that sections are aligned to the right", () => {
  	const {getByText} = render(<BasicCourseTable classes = {classesLectureAndSections} />);
  	expect( getByText("0101").style.textAlign).toBe("right");
  });
```

# Acceptance Criteria

- [ ] In courses search results, fields in the results will always be left aligned whether it's a primary (lecture) or a secondary (discussion section).
- [ ] This is true of all fields on the table.

**Comment by hamthony63** [comment]
5pm-2-fixResultsTable
