### ISSUE TITLE
Submit and Download CSV buttons on the homepage should be separated slightly (Download CSV button should be moved down slightly)

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#111]
# User Story

As a user I can clearly click on the Submit and Download CSV buttons.

# Acceptance Criteria

- [ ] There is noticeable gap between Submit and Download CSV buttons

# Implementation Todos

Front end:

- [ ] Add a `marginTop: "1rem"` to `style` property in Download CSV Button

Testing:

- All previous tests still pass

Guidance/Information:
- Changes should be in [`javascript/src/main/pages/Home/Home.js`](https://github.com/ucsb-cs156-w21/proj-ucsb-courses-search/blob/66e9ff8b601ec856091c4ad0bc825bd8c40e36a0/javascript/src/main/pages/Home/Home.js#L42)
- Check more on inline styling [here](https://reactjs.org/docs/dom-elements.html#style)

**Comment by DLohn** [comment]
The name of our branch is 5pm-3-fixButtonSpacing.

**Comment by andrewhlu** [comment]
Just an FYI, you shouldn't need to close issues manually unless you're deliberately choosing to not implement the issue. If you link the issue to its corresponding PR (either using a closing keyword or by adding it on the right sidebar), and the PR gets merged into the main branch, the issue will close itself automatically.
