### ISSUE TITLE
Make Navbar collapsible for smaller viewports

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#114]
# User Story

As a user I can use the navigation bar when I am on a mobile device or in a smaller window.

# Acceptance Criteria

- [x] The Navbar is responsive for smaller width windows

# Implementation Todos

Front end:

- [x] Add an `expand="lg"` property to the Navbar (this is a breakpoint)
- [x] Add a `<Navbar.Toggle />` tag to enable hamburger menu
- [x] Wrap all nav items with a `<Navbar.Collapse>` tag

Testing:

- All previous tests still pass

Guidance/Information:
- Changes should be in [`javascript/src/main/components/Nav/AppNavbar.js`](https://react-bootstrap.github.io/components/navbar/#navbars-mobile-friendly)
- Refer to this [example](https://react-bootstrap.github.io/components/navbar/#navbars-mobile-friendly)
    - Notice the Navbar item collapse into a hamburger menu if the window is small enough
```javascript
<Navbar expand="lg">
    <Navbar.Toggle />
    <Navbar.Collapse>
        <Nav>
            ...
        </Nav>
        ...
        <Nav>
            ...
        </Nav>
    </Navbar.Collapse>
</Navbar>
```

**Comment by codysasaki** [comment]
Branch Name: 5pm-4-FixNavbar
