### ISSUE TITLE
Add a note to specify that search by instructor only takes last name

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#115]
# User Story

* As a user that wants to search by instructor
* I can see instructions for entering instructor name
* So that I know to only enter the last name of the instructor

# Discussion

On the page for `https://proj-ucsb-courses-search.herokuapp.com/history/instructor` which looks like this:

![image](https://user-images.githubusercontent.com/1119017/108121390-976e8380-7057-11eb-87ac-48eb1c06ea36.png)

It may not be clear to the user what they should enter.

Compare the form for entering courses from proj-ucsb-cs-las, which has little hints under each field:

![image](https://user-images.githubusercontent.com/1119017/108121563-d7356b00-7057-11eb-9728-e06fa9809780.png)

These are provided by the `<Form.Text>` elements in the file `javascript/src/main/components/Courses/CourseForm.js` inside https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las 

We can use a similar pattern here to specify an instruction `Enter instructor last name only.`  

It may also be helpful to add something like: 
`If there are multiple instructors with the same last name, do a search by last name first to determine how the instructor first name is abbreviated, e.g. WANG R K, WANG Y X, WANG Y F, etc. and then repeat the search.`

# Acceptance Criteria

- [ ] Under the instructor name field on the page `https://proj-ucsb-courses-search.herokuapp.com/history/instructor` there is text giving the user hints about how to enter the instructor name.

# Testing

- [ ] There is a test looking for these hints.    The course staff can help you find example code for writing this test.

**Comment by WadeVaresio** [comment]
Branch 5pm-3-addInstructorLastName addresses this issue.
