### ISSUE TITLE
About page should have an actual description of the application

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#123]
# User Story

As a user I can go to the About page to learn more on what the app is for

# Acceptance Criteria

- [ ] About page should have an accurate description of the app
- [ ] About page has a Purpose heading describing the purpose of the app
- [ ] About page has a Features heading describing the features of the app
- [ ] About page has a section mentioning CS156's role in creating/maintaining CS LAs app along with a link to the GitHub

# Implementation Todos

Front end:

- [ ] Left align headings
- [ ] Main Heading should be About Us
- [ ] Subheadings: Purpose, Features, Team
- [ ] Short description under each subheading

Back end:

None

Testing:

- [ ]  All previous tests still pass

Guidance/Information:
- You have Creative Freedom to design the About page along with any content in it.  You might look at what Prof. Conrad wrote in the #proj-ucsb-courses-search channel on the Slack about the overall purpose of the app, and/or ask the TAs/LAs that are familiar with the app for guidance.
- Changes should be in `javascript/src/main/pages/About/About.js`
- More on Typography in [Bootstrap](https://getbootstrap.com/docs/4.0/content/typography/)
- Headings are usually wrapped in `<h1>` tags with subheadings `<h2>`, `<h3>` and so on.
- Content after headings are wrapped in `<p>` tags
- About page already has an example of this heading then paragraph layout, we just need to change it and add more headings!

**Comment by Tuckwilliger** [comment]
branch name: 5pm-2-aboutpage

Task to write an about page description

**Comment by pconrad** [comment]
@Tuckwilliger I wonder if you closed this by mistake?  I'm reopning, but if you really wanted to close it, let me know why you needed to do that.
