### ISSUE TITLE
Update the title text to something relevant

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#124]
# User Story

As a user I can see the correct app name from the tab, so I don't have to click on the tab to know what the webpage is.

That is, instead of seeing this:

![image](https://user-images.githubusercontent.com/1119017/101975395-188d4280-3bf1-11eb-9bf8-e2d078c6d04b.png)

I want to see the text "UCSB Courses Search" in place of "Demo CRA + Spring App"

# Acceptance Criteria

- [ ] The tab displays the title "UCSB Courses Search", no matter what page the user navigates to

# Discussion

In the file `javascript/public/index.html` we find this code:

```html
 <title>Demo CRA + Spring App</title>
```

By changing that to 

```html
 <title>UCSB Courses Search</title>
```

we can make it so that this text appears on the browser tab when this page is loaded.  This will affect every page in the app. 

# Implementation Todos

Front end:

- [ ] The title for the main index page (filename: `javascript/public/index.html` should be updated to the proper name

Testing:

- [ ] No automated test for this change is needed. (The change is in a static `index.html` file, not in Java or JavaScript code, and we don't currently have any test infrastucture in place to test for items in the `<head>` section of the static `index.html` file of the app.)
- [ ] All previous tests still pass

# Implementation Details: 

Students can follow example in this PR: https://github.com/ucsb-cs156-w21/demo-spring-react-minimal/pull/7

**Comment by dshamtob** [comment]
The name of our branch is updateTitle.
