### ISSUE TITLE
Update the FAVICON to something relevant.

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#125]
# User Story

* As a user
* I can see a favicon relevant to the project
* So that I can easily spot browser tabs for this app

# Discussion

In a browser, there are typically icons on each tab that identify the application.  For example, these:

![image](https://user-images.githubusercontent.com/1119017/108134964-0a81f500-706c-11eb-8475-4e7ea223674d.png)

At the moment, this app has a favicon that is left over from the Create React App template... it looks like this:

![image](https://user-images.githubusercontent.com/1119017/108134990-18d01100-706c-11eb-8012-664fcb510dd0.png)

Instead, we want to replace this with a placeholder icon found in this repo:

https://github.com/ucsb-cs156-w21/placeholder-favicons

# Acceptance Criteria

- [x] When the application is loaded in a browser, we see the correct favicon for this app

# Implementation todos

- [x] Replace the file `javascript/public/favicon.ico` with the `favicon.ico` file from the appropriate directory
- [x] Replace the contents of the file `javascript/public/manifest.json` with the contents of the file `site.webmanifest` from the appropriate directory
- [x] Upload the `.png` files from the appropriate directory in https://github.com/ucsb-cs156-w21/placeholder-favicons into the directory `javascript/public`.
- [x] Delete the files `javascript/public/logo192.png` and `javascript/public/logo192.png` 
- [x] In the file `javascript/public/index.html`, replace the lines as shown below

# Lines to replace in `javascript/public/index.html`:

Replace:
```
    <link rel="apple-touch-icon" href="%PUBLIC_URL%/logo192.png" />
```

With 
```
   <link rel="apple-touch-icon" sizes="180x180" href="%PUBLIC_URL%/apple-touch-icon.png">
   <link rel="icon" type="image/png" sizes="32x32" href="%PUBLIC_URL%/favicon-32x32.png">
   <link rel="icon" type="image/png" sizes="16x16" href="%PUBLIC_URL%/favicon-16x16.png">
```

# Testing

Because this is in static code rather than Java or JavaScript code, we do not currently have a good way to write automated tests for this.  So this should be tested manually by implementing first on localhost, then by deploying the branch on the team's QA site.

Also, all existing tests should still pass.

**Comment by henryanderson64** [comment]
5pm-2-favicon
