### ISSUE TITLE
Implement show/hide of cancelled, closed, and full classes, using component developed in #141

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#150]
# User Story

As a user I can toggle whether or not I want to see cancelled, closed, and full classes in the course table so that I can narrow down my choices to only available courses.

# Discussion

There is a separate issue, #141 to create a new component for the UI with these controls on it.  I suggest completing that issue first, and then implementing the changes needed to incorporate that into the app (those are in this issue).

# Acceptance Criteria

- [x] There exist checkboxes to specify whether closed, full, or canceled courses are displayed or not.
- [x] When the checkboxes are checked/unchecked the course display updates accordingly.
- [x] When the lecture is closed/canceled, hide the entire course. 
- [x] If the sections are closed/canceled/full, hide only the sections not the lecture if the lecture is not closed/canceled/full.

# Implementation Todos

Note: You could continue the work of PR #74 or start from scratch. If you are continuing, talk to staff about color choices/possible bugs.

Front end:

- [x] Add a checkbox or similar above the course table to toggle whether or not courses which are cancelled/closed/full are shown or not.
- [x] When the checkbox is checked, only show courses that are open in the results table.

Back end:
Nothing to do.

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

**Comment by amarantini** [comment]
What should we do if there's a class with a lecture session is full but discuss session is not full, or vice versa?
Same with closed and canceled.
