### ISSUE TITLE
Create Total Courses by Department page

### ISSUE THREAD

**Issue by mara-downing** [ucsb-cs156-w21/proj-ucsb-courses-search#151]
# User Story

As a user I can find a page displaying a table of total courses per department, so that I can quickly see the relative sizes of the different departments.

# Acceptance Criteria

- [x] In the Statistics dropdown menu, there should be an entry that links to an "Total Courses by Department" page
- [x] There is a table on that page which displays a row for each department.
- [x] There is a form on the page for the user to choose a quarter to be analyzed.

# Implementation Todos

Front end:

- [x] Add a service that allows the page to fetch the chosen department information and set the department JSON in order for it to display.

Back end:

- [x] Add a endpoint to the StatisticsController file that will service fetch requests from the frontend.
- [x] In the StatisticsController file, use MongoDB and aggregate the quarter/department data and return as JSON.

Testing:

- [x] Front end tests pass and there is adequate coverage
- [x] Back end tests pass and there is adequate coverage

**Comment by WadeVaresio** [comment]
Branch 5pm-3-totalCoursesByDept works on this issue.
