### ISSUE TITLE
GE Search: Download results as CSV

### ISSUE THREAD

**Issue by mara-downing** [ucsb-cs156-w21/proj-ucsb-courses-search#156]
# User Story

As a user, I can see a button named "download as CSV" on the "GE Search" tab, were clicking on that button will give me the results of that search in CSV format.

# Acceptance Criteria
- [x] "GE Search" has a Download as CSV button which downloads the search results to a csv file.

# Implementation Todos

Front end:

- [x] Use BasicCourseTable allowExport prop to generate csv and button.

Back end:

- Nothing to do

Testing:

- [x] Front end tests pass and there is adequate coverage

**Comment by codysasaki** [comment]
Branch:  5pm-4-geDownloadAsCSV
