### ISSUE TITLE
Search by Instructor: Download results as CSV

### ISSUE THREAD

**Issue by mara-downing** [ucsb-cs156-w21/proj-ucsb-courses-search#157]
# User Story

As a user, I can see a button named "download as CSV" on the "Search by Instructor" tab, were clicking on that button will give me the results of that search in CSV format.

# Acceptance Criteria
- [x] "Search by Instructor" has a Download as CSV button which downloads the search results to a csv file.

# Implementation Todos

Front end:
- [x] Use BasicCourseTable allowExport prop to generate csv and button.
- [x] Button displayed on "Search by Instructor" page that downloads csv.

Back end:

- Nothing to do.

Testing:

- [x] Front end tests pass and there is adequate coverage

**Comment by DerpDerek** [comment]
Branch: 5pm-4-InstructorSearch-DownloadAsCSV
https://github.com/ucsb-cs156-w21/proj-ucsb-courses-search/tree/5pm-4-InsturctorSearch-DownloadAsCSV
