### ISSUE TITLE
Placeholder for add course button

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#173]
Add to the component `javascript/src/main/components/BasicCourseSearch/BasicCourseTable.js` in the table, a new column, all the way at the right hand side, for controls.  It just to the right of the "Unit" column.

For an example of a table that has buttons in it, see: `javascript/src/main/components/Schedule/ScheduleTable.js`

You'll need to conditionally render the buttons though: sometimes an add button, and sometimes NO add button.

In this new column, we'll place an add button ONLY when we have either a
*  a discussion section 
* a lecture section that HAS no discussion sections.

For now, the button does nothing... but in this story, the point is to get the button on the right courses, and have it NOT appear on the ones where it should not appear.

Making the button do something useful, i.e. add the course, is for story #177

**Comment by pconrad** [comment]
Estimate this as a 20 point story.

**Comment by Tuckwilliger** [comment]
branch name: 5pm-2-addbtn
