### ISSUE TITLE
Show page for personal schedules

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#174]
On the page <https://proj-ucsb-courses-search.herokuapp.com/schedule> we can see a list of all the personal schedules.

<img width="1094" alt="image" src="https://user-images.githubusercontent.com/1119017/109565695-b0375a00-7a97-11eb-9b0a-934c8eb86eca.png">

What want to do is create a new page on the front end side at the addresses 
* https://proj-ucsb-courses-search.herokuapp.com/schedule/1
* https://proj-ucsb-courses-search.herokuapp.com/schedule/2
* https://proj-ucsb-courses-search.herokuapp.com/schedule/3

etc.

Each of those pages will have, at the very top, the information already displayed on the index page https://proj-ucsb-courses-search.herokuapp.com/schedule for that ONE schedule,  but it will also have a place where the actual schedule will appear later.

For example, the show page for * https://proj-ucsb-courses-search.herokuapp.com/schedule/4 might have just this information on it:

<img width="1062" alt="image" src="https://user-images.githubusercontent.com/1119017/109565748-c47b5700-7a97-11eb-9356-35f0d0b0436f.png">

And the show page for https://proj-ucsb-courses-search.herokuapp.com/schedule/5 would have:

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/1119017/109565778-d0671900-7a97-11eb-8013-e3360ce263b2.png">
<img width="1053" alt="image" src="https://user-images.githubusercontent.com/1119017/109565795-d5c46380-7a97-11eb-9f34-55713569d678.png">

On the page https://proj-ucsb-courses-search.herokuapp.com/schedule, we want the name of each schedule to be a link to the show page.

That actual schedule can reuse the component BasicCourseTable, and it will show just the courses that are on that particular schedule.   FOR THIS STORY, YOU ONLY NEED TO IMPLEMENT THE PART THAT SHOWS, on the show page, the:

* id, name, description, quarter, edit button and delete button.

You do NOT need to do the course table yet.  Just leave a comment where it will appear later.  Adding the schedule to the bottom of the show page is issue #176 

Ask the staff for examples of "show pages" in the app so you know what we are talking about.

One easy way to implement a show page is to use the same component on the index page, but just pass it a JSON array that has a single element in it, instead of multiple elements.  That allows you to reuse the table that you used on the index page.

**Comment by jin-jeong** [comment]
5pm-2-personalShowPage
