### ISSUE TITLE
Modify ScheduleItem entity

### ISSUE THREAD

**Issue by pconrad** [ucsb-cs156-w21/proj-ucsb-courses-search#175]
# User Story

Note: there is no user story for this issue.  This updated an existing database table— by itself this does nothing for the end user.  However, this story makes it possible to implement stories #176 and #177  each of which DOES have a user story associated with it.

# UPDATE to make this easier:

- [ ] delete the files `src/main/java/edu/ucsb/courses/controllers/ScheduleItemController.java` and `src/test/java/edu/ucsb/courses/controllers/ScheduleItemControllerTests.java`

They are not currently being used.  We can build them back up, slowly, as they are needed, looking at old commits where needed.

# Acceptance Criteria

- [x] There is an `@Entity` class called `ScheduleItem` that has these fields: `id`, `sched_id`, `lecture`, `discussion`.  The `sched_id` is actually a reference to an entity in the Schedule table, so we should use that pattern of @ManyToOne etc. see in the ucsb-cs-las app.)  (NOTE: This entity already exists; just needs to be modified to the correct fields.)
- [x] There is a new `@Repository` called ScheduleItemRepository (Already exists)
- [ ] There is a `data.sql.SAMPLE` file that populates this table and the Schedule table when running on localhost.

# Discussion

Each personal schedule item should have these fields:
* id (normal auto increment long)
* sched_id (id of an entry in the personal schedule table)
* lecture (string, enroll code of the lecture)
* discussion (string, enroll code of the discussion) (the discussion might be null)

Initially, you will create a data.sql.SAMPLE file that populates this table with some sample data.

Here's an example of a data.sql.SAMPLE:
https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las/blob/main/src/main/resources/data.sql.SAMPLE

In your case, create at least two "personal schedules", and then put a few courses on those schedules in the data.

That will set you up to be able to test the page that SHOWS the personal schedule on the personal schedule show page.

# Additional Notes

It appears that there is already a ScheduleItem table, but it doesn't quite have the fields that we would want it to have.

`src/main/java/edu/ucsb/courses/entities/ScheduleItem.java` is the class.

It has fields:
```
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Column(nullable = false)
    private String courseId;
    @Column(nullable = false)
    private String enrollCode;
    @Column(nullable = false)
    private String userId;
    @Column(nullable = false)
    private Long scheduleId;
```
I think what we want instead is this:

* id (normal auto increment long)  (already correct)
* sched_id (id of an entry in the personal schedule table) (already correct, as "scheduleId", but I'd suggest a small change; we'll come back to this...
* lecture (string, enroll code of the lecture)  (this and the next one replace the single enrollCode)
* discussion (string, enroll code of the discussion) (the discussion might be null, so nullable = true for this one.)

Also, the field for userId is correct (though we'll make one change... more on that in a sec.)

```
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;
    @Column(nullable = false)
    private String courseId;
    @Column(nullable = false)
    private String enrollCode;
    @Column(nullable = false)
    private String userId;
    @Column(nullable = false)
    private Long scheduleId;
```

The courseId field and userId field are references to other tables and there is a better way to do that.

Instead of:
```
    @Column(nullable = false)
    private String userId;
```

We use:
```
@ManyToOne  
@JoinColumn(name = "app_user_id") 
private AppUser appUser;
```

And instead of
```
@Column(nullable = false)
private Long scheduleId;
```

We use:
```
@ManyToOne  
@JoinColumn(name = "schedule_id") 
private Schedule schedule;
```

This allows us to directly access the schedule object and the user object from the `ScheduleItem` object.

**Comment by phtcon** [comment]
For the `@ManyToOne` thing, you can reference:

https://github.com/ucsb-cs156-w21/proj-ucsb-cs-las/blob/main/src/main/java/edu/ucsb/ucsbcslas/entities/TutorAssignment.java

as an example, and perhaps also look at the tests in the corresponding test file.

**Comment by hamthony63** [comment]
branch name: 5pm-2-modifyScheduleItem
