### ISSUE TITLE
List Full Course Title

### ISSUE THREAD

**Issue by kunalhandaUCSB** [ucsb-cs156-w21/proj-ucsb-courses-search#68]
# User Story

As a user I can see the full course title in the table so that I can be sure about which course I am looking at.

# Acceptance Criteria

- [ ] Every course should have a full course title

# Implementation Todos

Front end:

- [ ] Modify the proper component to display the full course title

Back end:

- No changes needed

Testing:

- [ ] Front end tests pass and there is adequate coverage
- [ ] Back end tests pass and there is adequate coverage

**Comment by mara-downing** [comment]
I'm sorry, I believed there was a full course title listed in the JSON--i was wrong. For now you can work on the other 3 issues on your Kanban board.
